### ISSUE TITLE
Why did u remove Yuzu support? 

### ISSUE THREAD

**Issue by alerion921** [Ecks1337/RyuSAK#17]
I would like to use this software but i prefer yuzu over ryujinx, can you please add back yuzu support?

**Comment by metalmight** [comment]
I don't think it ever had Yuzu support. EmuSak did but this is RyuSak. My question is, why not include Yuzu?

**Comment by alerion921** [comment]
Yuzu code was removed, this is essentialy a fork from the original code that had yuzu support.

**Comment by Ecks1337** [comment]
Duplicate of #7, Closing
