### ISSUE TITLE
Keys Button Broken

### ISSUE THREAD

**Issue by emir4169** [Ecks1337/RyuSAK#21]
**Describe the bug**
When the download keys button is pressed. nothing happens.

**To Reproduce**
1. Click on 'DOWNLOAD KEYS'
2. See error

**Expected behavior**
The keys get downloaded

**Screenshots**
(how tf do i do this for this problem)

**Desktop (please complete the following information):**
- OS: Windows
- Version 1.5.0

**Additional context**
Only the download firmware button works.

**Comment by emir4169** [comment]
This problem isnt just on my pc, it happens on a person i was trying to help about prod. keys and firmware downloads

**Comment by Ecks1337** [comment]
Keys download just fine for me, so you'll have to provide more information. At the very least show the error you refer to.

**Comment by emir4169** [comment]
THERE IS NO ERROR IT JUST DOESNT DO ANYTHING

**Comment by Ecks1337** [comment]
The keys are hosted on sigmapatches.coomer.party, I assume your ISP blocks this site
