### ISSUE TITLE
Where are shader caches uploaded to?

### ISSUE THREAD

**Issue by kartikynwa** [Ecks1337/RyuSAK#23]
I tried uploading the shader cache for a game and got a message saying that another submission with more shaders has been made but is awaiting approval.

Where are they uploaded to? I could test these uploads to help the approval process.

**Comment by vesper8** [comment]
How often are uploaded shaders approved? I shared a few as well but didn't receive any feedback that it would need to be approved first. I was also surprised to see the number of games that have 0 shaders available.

**Comment by WeeJeWel** [comment]
They seem to be downloaded from here: https://hel1-1.mirror.lewd.wtf/archive/nintendo/switch/shaders/SPIR-V/

**Comment by kartikynwa** [comment]
> lewd.wtf

🤔

**Comment by Ecks1337** [comment]
Shaders are downloaded from https://mirror.lewd.wtf/archive/nintendo/switch/shaders/
We have changed the approval system so shader caches will be available in RyuSAK a lot faster!
