### ISSUE TITLE
Request: macOS build

### ISSUE THREAD

**Issue by DenzoNL** [Ecks1337/RyuSAK#24]
Now that we finally have a macOS build of RyujiNX, I'd like to request a macOS build of RyuSAK. From what I can see in the Electron Forge docs (https://www.electronforge.io/config/makers/dmg), it should only require extending `forge.config.js` and subsequently configuring GitHub Actions to also run the build job on a macOS runner.

I would've submitted a PR but I can't modify the GitHub Actions settings and from experience adding and testing a new CI pipeline can be something of an ugly mess if it doesn't work on the first try, since you need to push to trigger a new build.

Let me know what you think and if you need help testing the build :)

**Comment by karimlevallois** [comment]
Can we download shader caches for the macOS version via Linux for example, or do we actually need a macOS build to get the caches for our Apple Silicone models?

**Comment by Paulicat** [comment]
FYI I built this with npm run build and it works perfectly.
Hopefully you can provide prebuilts along with the Windows and Linux prebuilts.
Great work btw.
