### ISSUE TITLE
RyuSAK is available in AUR for archlinux

### ISSUE THREAD

**Issue by sukanka** [Ecks1337/RyuSAK#36]
There are two packages in ArchLinux User Repository:
* [ryusak](https://aur.archlinux.org/packages/ryusak): build from source, running with system electron
* [ryusak-bin](https://aur.archlinux.org/packages/ryusak-bin): official release binary

So could you please update the README?

**Comment by Ecks1337** [comment]
Thank you for creating a source package on the AUR, but I'd prefer to come up with a more official solution. If you could join the Discord we could discuss it.
I will update the readme with your package in the meantime. As for the binary package, it's out of date so I'll not add it.

**Comment by sukanka** [comment]
> Thank you for creating a source package on the AUR, but I'd prefer to come up with a more official solution. If you could join our Discord we could discuss it. I will update the readme with your package in the meantime. As for the binary package, it's out of date so I'll not add it.

Well, in fact, I'm using Yuzu,  which seems not supported by `ryusak`. 
Unfortunately,  I don't use discord. So when you find a more official solution (an official packager, for example), just tell me, I can add him/her to the maintainer list or transfer the package to him/her.
