### ISSUE TITLE
[Feature Request] Save management system

### ISSUE THREAD

**Issue by vesper8** [Ecks1337/RyuSAK#38]
In the past I've implemented a quick-save / quick-load feature for different games that would essentially just map a hotkey or a CLI cmd to doing a backup or restore of the save files for specific games. Also known as save scumming. I think that this would be a great feature to add to RyuSAK and it should be pretty easy to do since all save files are stored in the same place which happens to be inside the Ruyjinx folder too.

This would add quick-save/quick-load functionality to all the games that don't support it. Such as pretty much all roguelike/roguelite games. 

I know I would use this a lot!

Please consider adding this : )

**Comment by Ecks1337** [comment]
Since there is already a feature request for this to be implemented in Ryujinx there is no need for it to be implemented in RyuSAK. RyuSAK will only contain features the Ryujinx team refuse to support.

**Comment by vesper8** [comment]
Well it seems to me like they are refusing to add this feature. Specifically the feature that I proposed above is not at all the same one that was requested. I guess I made a mistake linking to the other feature request.. sad that you won't consider it.
