### ISSUE TITLE
RyuSAK won't detect any games on MacOS

### ISSUE THREAD

**Issue by goodforme100** [Ecks1337/RyuSAK#42]
Upon opening RyuSAK, it says "Loading Data" for a bit, then when it opens, it simply tells me to download Ryujinx and launch a game, which I had done both.

To reproduce, I simply installed RyuSAK normally using the arm dmg file.

I have found other people with similar issues, but no clear answer.

For context, I am running an M1 MacBook Pro with MacOS Ventura 13.1. Thanks in advance!

**Comment by ThijsGaming** [comment]
add the directory to ryusak as configuration

**Comment by goodforme100** [comment]
In Ryujinx? If you mean add my Ryujinx directory to RyuSAK, I've already done that

**Comment by ThijsGaming** [comment]
i'm sorry i don't know how to help you then

**Comment by goodforme100** [comment]
Its ok, thanks!

**Comment by Ecks1337** [comment]
Duplicate of #43
