### ISSUE TITLE
Use aria2 to download stuff

### ISSUE THREAD

**Issue by lockieluke** [Ecks1337/RyuSAK#45]
**Is your feature request related to a problem? Please describe.**
Not really, it's just for speeding things up, downloading firmwares took quite a long time.

**Describe the solution you'd like**
Use aria2 to download stuff like firmware and shaders, aria2 utilises multithreading to speed up download.

**Describe alternatives you've considered**
There isn't really an alternative

**Additional context**
Not much

**Comment by Ecks1337** [comment]
aria2 does not make sense for our use case
