### ISSUE TITLE
[Bug] Ryusak keeps loading data.

### ISSUE THREAD

**Issue by skyillusions** [Ecks1337/RyuSAK#46]
**Describe the bug**
I am stuck with the screen of loading data.

**To Reproduce**
Whenever I open the ryusak, it keeps loading data and the interface cannot be displayed. I ran the ryusak in the terminal and it said that

/Applications/RyuSAK.app/Contents/MacOS/RyuSAK ; exit;
renyida@renyidadeMBP ~ % /Applications/RyuSAK.app/Contents/MacOS/RyuSAK ; exit;
objc[3032]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x2365572e0) and /Applications/RyuSAK.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libGLESv2.dylib (0x105df13c8). One of the two will be used. Which one is undefined.
Error occurred in handler for 'load-components': v: request to https://api.github.com/repos/Ecks1337/RyuSAK/releases/latest failed, reason: socket hang up
    at ClientRequest.<anonymous> (/Applications/RyuSAK.app/Contents/Resources/app/.webpack/main/index.js:2:366914)
    at ClientRequest.emit (node:events:390:28)
    at TLSSocket.socketOnEnd (node:_http_client:471:9)
    at TLSSocket.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  erroredSysCall: undefined
}

**Expected behavior**
It seems that the error occured because of socket hang out. Could you please tell me how to fix it? I am stuck with it for several days.

**Screenshots**
<img width="1273" alt="image" src="https://user-images.githubusercontent.com/77843559/210469245-4fd30044-5c37-420c-a44d-e372e5f406a7.png">

**Desktop (please complete the following information):**
- OS: Macos 13.0.1 (22A400)
- Laptop: MacBook Pro 14 with M1 pro chip

**Comment by ForbAvalon** [comment]
Same issue but in PC.
I tried 1.5.0 1.6.0 and 1.6.1, none of it run well.

**Comment by kriou** [comment]
Delete RyuSAK, then decompress it again, put the decompressed RyuSAK into a folder named with only 26 letters, do not have special language text, if there is an agent, hang the agent, if you don’t need the agent, don’t hang it, and run again.

**Comment by MInecrafterPictures** [comment]
Same issue on my Windows PC using 1.6.1

**Comment by Lichtverbunden** [comment]
Same issue on my Windows 10 PC.

**Comment by fluxbeard** [comment]
Same issue for me on my MacBook Pro 16" M1 Pro with Ventura 13.1. Have tried 1.6.0 and 1.6.1.

**Comment by Ecks1337** [comment]
resolved by 1c29692

**Comment by notPlancha** [comment]
For me the new 1.6.2 is still stuck in loading

**Comment by Lichtverbunden** [comment]
For me as well.

**Comment by sabba90** [comment]
+1 is still stuck in loadiang data, version 1.6.2 and windows 11! It's been 2 days! Any news?

**Comment by IRaffo** [comment]
Still not working

**Comment by jonschtote** [comment]
same, used to work and now doesnt... Ive tried a full reinstall, deleting all ryusak data and still doesnt load after running setup

**Comment by notPlancha** [comment]
now it's working so maybe the server was down

**Comment by Foxlass** [comment]
not working

**Comment by AnubisACX** [comment]
> not working

Same, server is down or something.

**Comment by jdhau** [comment]
Not working here

**Comment by DidadoY** [comment]
not working

**Comment by Drakeye** [comment]
Still down

**Comment by notPlancha** [comment]
Maybe we just need a "is ryusak down" detector instead of commenting here
