### ISSUE TITLE
Allow us to open Ryujinx with a button

### ISSUE THREAD

**Issue by kevincrans** [Ecks1337/RyuSAK#5]
I really love this program and that it's released since 9 days, I couldn't figure out what to do with a zip.
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to start explorer to start it when I already have 20 windows open.

**Describe the solution you'd like**
I want to open it with the click of a button.

**Describe alternatives you've considered**
I considered the slow search menu, which is really good in Windows 11.

**Additional context**
I just thought, this isn't much of a hassle, especially since this is the 4th issue.

**Comment by Ecks1337** [comment]
I don't understand your problem. If you don't want to look for the Ryujinx exe every time, create a shortcut to it and have it on your desktop and/or pinned to your task bar..
