### ISSUE TITLE
Cant load shader Fire Emblem Engage

### ISSUE THREAD

**Issue by mngueki** [Ecks1337/RyuSAK#52]
Hello, when i use shader another game its ok. But when i download Fire Emblem Engage shader, my Ryujinx alway said that cant load shader its have problem. Can you check it

**Comment by Brawl345** [comment]
Same problem here on macOS, the newest shader (5583) can't be compiled because RyujiNX hangs at 1198. The older one (with 4000 something) worked fine.

**Comment by B-Wilhelm** [comment]
Same here! with newest shader (7143)

**Comment by PyroMikeGit** [comment]
Currently running into the same issue with the new shaders this is the error that pops up,
00:00:01.388 |I| GPU.MainThread Gpu LoadShaders: Loading 8352 shaders from the cache...
00:00:02.731 |E| GPU.AsyncTranslationThread.7 Gpu RecompileFromGuestCode: Error translating guest shader. Texture descriptor missing from the cache file.
00:00:02.738 |E| GPU.AsyncTranslationThread.4 Gpu RecompileFromGuestCode: Error translating guest shader. Texture descriptor missing from the cache file.
00:00:02.742 |E| GPU.AsyncTranslationThread.7 Gpu RecompileFromGuestCode: Error translating guest shader. Texture descriptor missing from the cache file.
00:00:02.743 |E| GPU.AsyncTranslationThread.4 Gpu RecompileFromGuestCode: Error translating guest shader. Texture descriptor missing from the cache file.
00:00:02.743 |E| GPU.AsyncTranslationThread.6 Gpu RecompileFromGuestCode: Error translating guest shader. Texture descriptor missing from the cache file.
00:00:02.744 |E| GPU.AsyncTranslationThread.0 Gpu RecompileFromGuestCode: Error translating guest shader. Texture descriptor missing from the cache file.
00:00:02.745 |E| GPU.AsyncTranslationThread.7 Gpu RecompileFromGuestCode: Error translating guest shader. Texture descriptor missing from the cache file.
00:00:02.745 |E| GPU.AsyncTranslationThread.2 Gpu RecompileFromGuestCode: Error translating guest shader. Texture descriptor missing from the cache file.
00:00:02.745 |E| GPU.AsyncTranslationThread.3 Gpu RecompileFromGuestCode: Error translating guest shader. Texture descriptor missing from the cache file.

Current total: (8352)
Firmware 16.0.0

**Comment by Sunshine-Leona** [comment]
Hello. Just wanted to write that I have the same problem. 

Texture desriptor missing from the cache file.

Any help would be appreciated.
