### ISSUE TITLE
Kirby and the Forgotten Land - 01004D300C5AE000

### ISSUE THREAD

**Issue by sykoe** [Ecks1337/RyuSAK#56]
Downloaded cache is corrupted

ryujinx log: 
00:00:01.010 |I| GPU.MainThread Gpu LoadShaders: Loading 13179 shaders from the cache...
00:00:01.014 |W| GPU.MainThread Gpu LoadShaders: Error loading the shader cache. The cache file is corrupted.
00:00:01.095 |I| HLE.GuestThread.19 Ptc LoadTranslations: 18295 translated functions loaded
00:00:01.129 |I| GPU.MainThread Gpu LoadShaders: Rebuilding 4 shaders...

**Comment by drizzt** [comment]
Why is it closed?
I have the same error: "Error loading the shader cache. The cache file is corrupted."
