### ISSUE TITLE
Downloaded shader cache crashes Mario Kart 8 on Linux with AMD GPU (RADV)

### ISSUE THREAD

**Issue by Kiwii** [Ecks1337/RyuSAK#57]
The provided shader cache for MK8D crashes Ryujinx LDN during shader compilation on Linux using an AMD GPU (Vega 64) with Mesa's RADV vulkan driver. Possibly a similar situation to #40 ?

Possibly relevant from log:

```
00:00:01.838 |W| GPU.AsyncTranslationThread.1 Gpu Log: Shader translator: Shader instruction Votevtg is not implemented.
00:00:02.042 |E| .NET ThreadPool Worker Gpu ConvertToVkFormat: Format R4G4Unorm is not supported by the host.
00:00:03.504 |E| .NET ThreadPool Worker Gpu ConvertToVertexVkFormat: Format R32G32B32A32Sscaled is not supported by the host.
```
Full log: [Ryujinx_1.1.0-ldn3.1.0_2023-03-09_23-38-54.log](https://github.com/Ecks1337/RyuSAK/files/10936772/Ryujinx_1.1.0-ldn3.1.0_2023-03-09_23-38-54.log)

Shader cache works fine in OpenGL mode. 

After deleting the cache, Vulkan works again.

Arch Linux
kernel 6.2.2
mesa 22.3.6
ryujinx ldn 3.1.0

**Comment by Zacharybinx34** [comment]
Same on windows with newest LDM Ryujinx

**Comment by dmitryfd** [comment]
> Same on windows with newest LDM Ryujinx and also with Smash Bros Ultimate Cache.
> 
> Terminal window says: ".NET ThreadPool Worker Gpu ConvertToVertexVkFormat:Format R32g32b32A32Sscaled is not supported by the host"

Same for me on the Windows build of Ryujinx 1.1.665 for the latest cached shaders for Mario Kart 8.
Used to work just yesterday, but refreshing the shaders (went from ~34K to ~30K) broke things.

**Comment by BlastBolt5** [comment]
Running into the same issue on arch (Ryujinx 1.1.625) and my m1 macbook air (Ryujinx 1.1.0-macos1) both Mario Kart 8 deluxe and Super Smash Bros Ultimate

**Comment by BindingOx** [comment]
any fix?

**Comment by Ecks1337** [comment]
broken shader cache has been deleted from the server

**Comment by alexstanbury** [comment]
Tried this a few moments ago and still seeing a crash

**Comment by BlastBolt5** [comment]
same here on macbook air m1, ventura

**Comment by Ecks1337** [comment]
fixed

**Comment by BlastBolt5** [comment]
mk8 still broken on Mac, I noticed the pc one got reset tho

**Comment by marcelosanchez** [comment]
same error on macbook air m1, ventura

**Comment by rrrcabral** [comment]
with me:
"00:00:27.650 |E| .NET ThreadPool Worker Gpu ConvertToVertexVkFormat: Format R32G32B32A32Sscaled is not supported by the host."
after downloaded shaders of mario kart 8 deluxe.

in latest public build of ryujinx. using VULKAN, on windows, gpu gtx 960 2gb, cpu amd ryzen 1600 af.

Shader cache works fine in OpenGL only.

**Comment by mijhaels** [comment]
mk8, smash ultimate, mario party superstars, super mario party broken on ryzen3400g+rx580 vulkan in debian 12

**Comment by mdrichardson** [comment]
Had the same just happen on Windows with MK8.
