### ISSUE TITLE
Add an updater

### ISSUE THREAD

**Issue by kevincrans** [Ecks1337/RyuSAK#6]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when... I have to download a new version manually, while last time I checked, it worked perfectly.

**Describe the solution you'd like**
An automatic check if u have the latest version, prompts if you want the newer version, downloads it and automatically restarts. Snapshots aren't necessary, with this fast progress, ppl can wait 6 days.

**Describe alternatives you've considered**
Only alternative is continue using the old keys/firmware, until support is dropped.

**Additional context**
I thought, let's suggest 2 luxury features, since it's already the best.

**Comment by Ecks1337** [comment]
There is already an updater in the Windows installer version. Updaters for other versions will not be implemented, instead it would be a better idea to push them to their respective repositories.
