### ISSUE TITLE
Yuzu support

### ISSUE THREAD

**Issue by hyoretsu** [Ecks1337/RyuSAK#7]
Any hope for it? Found this on the [Emulation wiki](https://emulation.gametechwiki.com/index.php/Emulator_files#Nintendo_Switch), interested about the shader cache sharing feature.

**Comment by Ecks1337** [comment]
Yuzu will not be supported

**Comment by AverageDood** [comment]
May I ask, why not? With EmuSAK having closed shop, it'd be nice to have once again a single program that supports both emulators. As an AMD iGPU user, most games work better on Yuzu's Vulkan than on Ryujinx's, for example

**Comment by metalmight** [comment]
> Yuzu will not be supported

You forgot to mention why.
