### ISSUE TITLE
Hy, Tears of the kingdom shader cache corrupt

### ISSUE THREAD

**Issue by ghost** [Ecks1337/RyuSAK#84]
TOTK Shaders corrupt on repo https://new.mirror.lewd.wtf/archive/nintendo/switch/shaders/SPIR-V/0100F2C0115B6000.zip

**Comment by MichaelW1980** [comment]
I have a similar issue with the Program itself. If i try to download the shaders, i get the error message "unable to fetch resource. please try again." Tried different internet connections and even VPNs, but it stay broken. If i check the shader folder, i see a zip file, but the file is corrupt.

**Comment by gbougiakas** [comment]
macOS native archive app cannot unzip the file. however I tried unzipping it with Keka and it works fine.

**Comment by MichaelW1980** [comment]
Well, for me, (under Windows 11)  RuySAK itself cant uncompress them, and neither can 7-zip and WinRAR, so... 🤷
