### ISSUE TITLE
Super Mario Bros Wonder game report not showned in RyuSAK launcher

### ISSUE THREAD

**Issue by FeddyLix17** [Ecks1337/RyuSAK#85]
**Description**
As the title says, Super Mario Bros Wonder report tags are not showned as if the issue on the [Ryujinx-Games-List](https://github.com/Ryujinx/Ryujinx-Games-List) repository didn't exist yet (but there is).

**Screenshots**

![image](https://github.com/Ecks1337/RyuSAK/assets/66442720/21354f5c-97f5-4c85-a8d4-abdf7bc62825)

![image](https://github.com/Ecks1337/RyuSAK/assets/66442720/16fe277d-fcd6-4fad-b249-b1712d3365bf)

**Desktop**
- OS: Windows11 22H2 Build 22621.2428
- RyuSAK Version: 1.6.2 (the latest while i'm writing)

**Comment by fejich** [comment]
I download the Super Mario Bros Wonder Shader, then the game won't start.
Is there any way to fix this besides deleting the shader?

![Z_S)FUFFJI2D1C P55(H4}X](https://github.com/Ecks1337/RyuSAK/assets/12195592/f5204b39-e34a-482b-9de8-fab81bfe4fd6)

**Comment by Bentheminernz** [comment]
RyuSAK is not made by the team behind Ryujinx and RyuSAK is no longer maintained so this issue is irrelevant
